### PR TITLE
Add support for `CLEAR` and `COUNTDOWN` update modes

### LINKED ISSUE #139: The media clock timer is not removed from screen when the update mode is set to CLEAR
If a `SetMediaClockTimer` RPC sent with the `updateMode` set to `CLEAR`, the media clock timer should be removed from the screen. Currently, nothing happens to the media clock timer.

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #139 and #140 

This PR adds proper support for the `CLEAR` and `COUNTDOWN` updateModes in the `SetMediaClockTimer` RPC.

### CODE REVIEW

**Comment by jacobkeeler** [comment]
@iCollin Just returning null makes the HMI look odd, since the background has 2 tones separated by the progress bar, not certain how to fix this easily

**Comment by NicoleYarroch** [comment]
Pause and resume do not work in count down mode. They work find in count up mode.

If I set the media clock to countdown:

```
Send RPC SetMediaClockTimer (request), id: 6
{
    audioStreamingIndicator = PAUSE;
    endTime = "{\n    hours = 0;\n    minutes = 0;\n    seconds = 0;\n}";
    startTime = "{\n    hours = 0;\n    minutes = 0;\n    seconds = 30;\n}";
    updateMode = COUNTDOWN;
}
```

And then pause, I would expect the playbar to stop at the position where I paused (i.e. If I paused 2 seconds into the countdown, I would expect the playbar to stop at 00:00:28). It actually resets the playbar to the full position and the label back to "00:00:00". The `audioStreamingIndicator` does update correctly. 

```
{
    audioStreamingIndicator = PLAY;
    updateMode = PAUSE;
}
```

When I try to resume, nothing happens (i.e. the playbar and label stay the same and do not count down). The `audioStreamingIndicator` does update correctly. 

```
{
    audioStreamingIndicator = PAUSE;
    updateMode = RESUME;
}
```

**Comment by jacobkeeler** [comment]
@NicoleYarroch Fixed in https://github.com/smartdevicelink/generic_hmi/pull/246/commits/458a3323c6f10f1676da6005d22d567a3ce89485

**Comment by NicoleYarroch** [comment]
@jacobkeeler 

I am getting a `REJECTED` result code when I send a `SetMediaClockTimer` for both `COUNTDOWN` and `COUNTUP` now. I made sure I was using the `MEDIA` template.

```
Request failed: SetMediaClockTimer (request), id: 7
{
    audioStreamingIndicator = PAUSE;
    endTime = "{\n    hours = 0;\n    minutes = 0;\n    seconds = 0;\n}";
    startTime = "{\n    hours = 0;\n    minutes = 0;\n    seconds = 30;\n}";
    updateMode = COUNTDOWN;
}, response: SetMediaClockTimer (response), id: 7
{
    resultCode = REJECTED;
    success = 0;
}
```

```
Request failed: SetMediaClockTimer (request), id: 8
{
    audioStreamingIndicator = PAUSE;
    endTime = "{\n    hours = 0;\n    minutes = 4;\n    seconds = 18;\n}";
    startTime = "{\n    hours = 0;\n    minutes = 0;\n    seconds = 0;\n}";
    updateMode = COUNTUP;
}, response: SetMediaClockTimer (response), id: 8
{
    resultCode = REJECTED;
    success = 0;
}
```

**Comment by jacobkeeler** [comment]
@NicoleYarroch That is Core rejecting the message because `endTime` is greater than `startTime`

**Comment by NicoleYarroch** [comment]
It turned out that the RPC was being rejected because the `appType` was not set to `MEDIA` in my test app (I changed it to test another PR). It was confusing because the `OnPermissionsChange` notification said the RPC was allowed and there was no `info` string in the returned response telling me why the `SetMediaClockTimer` RPC was rejected. 

The pause and resume look good except if I pause twice in a row or resume twice in a row, the progress label and progress bar jump to a random position. I would expect the HMI to just ignore the second pause or resume request.

**Comment by NicoleYarroch** [comment]
Everything looks good.

**Pull request merged**
